package com.synisys.trainngs.factory.impl;

import com.synisys.trainngs.factory.interfaces.ReportFooter;

public class AppspecificReportFooterImpl implements ReportFooter {

	public String getFooterString() {
		return "Report generated by DAD Tajikistan";
	}

}
